### ISSUE TITLE
Opening URLs in the app

### ISSUE THREAD

**Issue by mathiasnovas** [nurtext/active-collab-desktop#3]
Hi,

I've grown to really like having active collab as a desktop application. The only caveat being the lack of URL handling. If I click a link in, say, an AC-generated e-mail, the link will open my default browser instead of the desktop app. As a work-around I installed a redirect extension for chrome, sending me to a local script opening the app.

My question is, if possible, what data should I send to the app for it to display the page in which I was redirected from?

Thanks in advance,

Novas

**Comment by nurtext** [comment]
Hi Novas,

URL handling is implemented and opens any URL that should be opened in a new window and that is not part of the hosted activeCollab environment using `shell.openExternal()`. Therefore a `mailto:` URL should be opened in your default mail client.

See here for more details on how it's implemented:
https://github.com/nurtext/active-collab-desktop/blob/master/main.js#L111-L128

Btw: Could you please send me exact URL for the mailto link activeCollab generates? Please include the complete `href`-tag when responding. Thanks!

Cheers,
Cedric

**Comment by stianmartinsen** [comment]
I don't think Mathias meant links inside the app, but links in emails/browsers. When I click a link in an email, my default browser opens up. It would be nice if the app opened up instead.

Mathias' "hack" for doing this seems to involve having Chrome invoking the app from the command line. If so, can we pass a parameter to have the app navigate to a given URL?

**Comment by mathiasnovas** [comment]
@stianmartinsen That's exactly what I meant.

**Comment by nurtext** [comment]
@mathiasnovas Like explained before: All external URIs are opened via `shell.openExternal()` which should open in the default app defined by your OS. This is an internal Electron function on which I haven't got any influence. Could be a bug in Electron though.

**Comment by mathiasnovas** [comment]
It's the other way around. I'm sorry if my explanation wasn't very clear. 

My issue isn't with outgoing links within your app. I simply want any link, from any source or app, pointing to an AC-associated domain to open in your app instead of my default browser.

Picture this scenario: I receive an e-mail (in Mail.app) which contains a link to `app.activecollab.com/<some-id>`. Normally when I click this link, my default browser (Chrome) will show me the page. But instead of just showing me the page, I've installed a Chrome extension which triggers your app (via a PHP-script running `exec`) if the URL contains `app.activecollab.com`. This works fine, but of course, your app isn't aware of the URL — which makes this kind of pointless... 

Now, my question is whether or not there's any way to pass the URL as a parameter to your app?

**Comment by nurtext** [comment]
@mathiasnovas Now I got it. 😃 

I'm afraid this isn't possible because the external URI handler is configured to check against `app.activecollab.com` and `my.activecollab.com`. All other URIs are considered "external" and thus opened in your default browser. If I'd remove this check every external URI would be opened inside the app, which is something we really don't want to happen…

**Comment by mathiasnovas** [comment]
I'm suspecting we're still not on the same page here. Maybe I'm just very confused as to how your app works. However, I won't give up on this just yet… 😄 

Correct my if I'm wrong, but my understanding of your answer is that within your application you have an external URI handler which checks agains `app.activecollab.com` or `my.activecollab.com`. This is fine. I don't want this to behave differently. What I do want is for links coming from _any other application_ than your application containing either `app.activecollab.com` or `my.activecollab.com` to open in _your application_.

**Comment by nurtext** [comment]
@mathiasnovas Oh my god. I'm so sorry.  😁 I'm still afraid that this isn't possible at the moment. For sure apps can be assigned as default apps for custom protocols, but since activeCollab is using a standard protocol schema `http(s)://` we can't hook right into it. It would be possible with a custom procotol like `ac://` or `activecollab://` though…
