### ISSUE TITLE
Can`t Access Account

### ISSUE THREAD

**Issue by FGuttm** [nurtext/active-collab-desktop#4]
Hi,

I`m using activecollab desktop for windows *86 the newest version. From the beginning of this week all our employee started having issues with the app. When opening the app we get an empty page. I have attached a link to a screenshot of how it looks like.

Please advise.

Thank you.

![](https://lh3.googleusercontent.com/-yOiSJxLhF28/WXeCmZu2N-I/AAAAAAAAAa8/mIHbLwiM53g6oyszdOL3Z5f7vGFWF7hMwCL0BGAYYCw/h151/2017-07-25.png)

**Comment by nurtext** [comment]
The app currently only works with Cloud-Accounts from ActiveCollab. The text states you haven't one.

**Comment by FGuttm** [comment]
We do have a cloud account and we linked the desktop app to it.

**Comment by nurtext** [comment]
Okay, will have a look at it.

**Comment by FGuttm** [comment]
Any updates?

**Comment by nurtext** [comment]
@FGuttm not yet as I'm very busy atm.

**Comment by tallcoder** [comment]
I can't access my self-hosted account using this desktop app. Even though there are instructions for how to access self-hosted.

**Comment by tallcoder** [comment]
I was able to fix this by editing the source, then building. Consider this closed, but the instructions won't work.
