### ISSUE TITLE
Create an account? 

### ISSUE THREAD

**Issue by infopirate** [nurtext/active-collab-desktop#5]
When running the application for the first time, I am presented with this screen >
https://ibb.co/gOcPv7

Wondering how I go about creating an account, sorry for the oversight, just dont see an easy entrance into Active Collab from this window... 
-

Active Collab Desktop 0.7.2
linux x64 4.13.0-32-generic

**Comment by nurtext** [comment]
ActiveCollab is a paid service, thus you need to have an account and this inofficial app doesn't provide an account creation screen. Please refer to ActiveCollab: https://activecollab.com/pricing

**Comment by infopirate** [comment]
Interesting, thanks for the info!
